# Generated by Django 5.2.9 on 2026-01-18 00:35

import bot_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('language', models.CharField(default='uz', max_length=50)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchisi',
                'verbose_name_plural': 'Bot foydalanuvchilari',
            },
        ),
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('total_rides', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rating', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Yo'lovchi",
                'verbose_name_plural': "Yo'lovchilar",
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('translate', models.JSONField(default=bot_app.models.default_language)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('translate', models.JSONField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.city')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(default='', max_length=200, verbose_name='Haydovchi ismi')),
                ('total_rides', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rating', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10, verbose_name='Haydovchi xolati')),
                ('amount', models.IntegerField(default=150000, verbose_name="Haudovchi mablag'i")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_from', related_query_name='driver_from', to='bot_app.city')),
                ('to_location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_to', related_query_name='driver_to', to='bot_app.city')),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('telegram_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.driver')),
            ],
            options={
                'verbose_name': "Haydovchi pul o'tkazmasi",
                'verbose_name_plural': "Haydovchi pul o'tkazmalari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('arrived', 'Arrived'), ('started', 'Started'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='created', max_length=10)),
                ('order_type', models.CharField(choices=[('travel', 'Travel'), ('delivery', 'Delivery')], default='travel', max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.driver')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerToDriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.driver')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.order')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.passenger')),
            ],
            options={
                'verbose_name': "Buyurtmaga yo'lovchi izohi",
                'verbose_name_plural': "Buyurtmaga yo'lovchi izohlari",
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('from_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_city', to='bot_app.city', verbose_name='Boshlanish')),
                ('to_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_city', to='bot_app.city', verbose_name='Tugash')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.route'),
        ),
        migrations.CreateModel(
            name='RouteCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cashback', models.FloatField(default=0.001, verbose_name='Safar uchun keshbek %')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_settings', to='bot_app.route')),
            ],
            options={
                'verbose_name': "Yo'nalish keshbeki",
                'verbose_name_plural': "Yo'nalish keshbeklari",
            },
        ),
        migrations.CreateModel(
            name='PassengerTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('from_location', models.JSONField(default=bot_app.models.default_location)),
                ('to_location', models.JSONField(default=bot_app.models.default_location)),
                ('comment', models.TextField(default='')),
                ('cashback', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.IntegerField(default=1)),
                ('has_woman', models.BooleanField(default=False)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.route')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.tariff')),
            ],
            options={
                'verbose_name': 'Sayohat',
                'verbose_name_plural': 'Sayohatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('from_location', models.JSONField(default=bot_app.models.default_location)),
                ('to_location', models.JSONField(default=bot_app.models.default_location)),
                ('comment', models.TextField(default='')),
                ('cashback', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.route')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.tariff')),
            ],
            options={
                'verbose_name': 'Pochta',
                'verbose_name_plural': 'Pochtalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to='bot_app.route')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff', to='bot_app.tariff')),
            ],
            options={
                'verbose_name': "Yo'nalish narxlari",
                'verbose_name_plural': "Yo'nalish narxlari",
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=200, unique=True)),
                ('car_model', models.CharField(max_length=200)),
                ('car_color', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='bot_app.driver')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.tariff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('from_city', models.F('to_city')), _negated=True), name='check_from_to_not_equal', violation_error_message="Boshlanish va tugash shaharlari bir xil bo'lishi mumkin emas!"),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(condition=models.Q(('from_city__isnull', False), ('to_city__isnull', False)), fields=('from_city', 'to_city'), name='unique_from_to_cities', violation_error_message="Bu yo'nalish mavjud"),
        ),
        migrations.AddConstraint(
            model_name='cityprice',
            constraint=models.UniqueConstraint(fields=('route', 'tariff'), name='unique_route_tariff'),
        ),
    ]
