# Generated by Django 5.2.9 on 2026-01-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='route_id',
            new_name='route',
        ),
    ]
