# Generated by Django 5.2.8 on 2025-11-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengertravel',
            name='from_location',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='to_location',
            field=models.JSONField(default=dict),
        ),
    ]
