# Generated by Django 5.2.8 on 2025-11-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botclient',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='botclient',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='botclient',
            old_name='tg_id',
            new_name='telegram_id',
        ),
        migrations.AddField(
            model_name='botclient',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botclient',
            name='language',
            field=models.CharField(default='uz', max_length=50),
        ),
        migrations.AddField(
            model_name='botclient',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='botclient',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='botclient',
            name='total_rides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='botclient',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
