# Generated by Django 5.2.9 on 2026-01-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('searched', 'Searched'), ('assigned', 'Assigned'), ('arrived', 'Arrived'), ('started', 'Started'), ('ended', 'Ended'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='created', max_length=10),
        ),
        migrations.CreateModel(
            name='PassengerReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.order')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.passenger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
