# Generated by Django 5.2.9 on 2026-01-05 15:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botclient',
            options={'verbose_name': 'Bot foydalanuvchisi', 'verbose_name_plural': 'Bot foydalanuvchilari'},
        ),
        migrations.AddField(
            model_name='passengerpost',
            name='commit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passengerpost',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengertravel',
            name='commit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passengertravel',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 5, 15, 5, 54, 759598, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='amount',
            field=models.IntegerField(default=150000, verbose_name="Haudovchi mablag'i"),
        ),
        migrations.AlterField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='Haydovchi ismi'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10, verbose_name='Haydovchi xolati'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
