# Generated by Django 5.2.9 on 2026-01-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_alter_order_status_passengerreject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengertodriverreview',
            name='driver',
        ),
    ]
