# Generated by Django 5.2.8 on 2025-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_rename_joined_at_botclient_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('travel_class', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('business', 'Business')], default='standard', max_length=200)),
                ('passenger', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('has_woman', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
