# Generated by Django 5.2.9 on 2026-01-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_rename_route_id_driver_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='route',
            new_name='route_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_class',
        ),
    ]
