# Generated by Django 5.2.9 on 2026-01-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_alter_botclient_options_passengerpost_commit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerpost',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
