# Generated by Django 5.2.8 on 2025-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_alter_passengertravel_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengertravel',
            name='driver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passengerpost',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('arrived', 'Arrived'), ('started', 'Started'), ('on_the_way', 'On The Way'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('arrived', 'Arrived'), ('started', 'Started'), ('on_the_way', 'On The Way'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='created', max_length=10),
        ),
    ]
