# Generated by Django 5.2.8 on 2025-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_passengertravel_driver_alter_passengerpost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('business', 'Business')], default='economy', max_length=200),
        ),
    ]
