# Generated by Django 5.2.9 on 2026-01-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_remove_passengertodriverreview_driver'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='passengertodriverreview',
            constraint=models.UniqueConstraint(fields=('order', 'passenger'), name='uniq_review_per_order_per_passenger'),
        ),
    ]
