# Generated by Django 5.2.9 on 2026-01-10 06:02

import bot_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_alter_passengerpost_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('translate', models.JSONField(default=bot_app.models.default_language)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cityprice',
            options={'verbose_name': "Yo'nalish narxlari", 'verbose_name_plural': "Yo'nalish narxlari"},
        ),
        migrations.RemoveField(
            model_name='cityprice',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cityprice',
            name='comfort',
        ),
        migrations.RemoveField(
            model_name='cityprice',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='cityprice',
            name='economy',
        ),
        migrations.RemoveField(
            model_name='cityprice',
            name='standard',
        ),
        migrations.AddField(
            model_name='cityprice',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('from_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_city', to='bot_app.city')),
                ('to_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_city', to='bot_app.city')),
            ],
        ),
        migrations.AddField(
            model_name='cityprice',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to='bot_app.route'),
        ),
        migrations.AddField(
            model_name='cityprice',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff', to='bot_app.tariff'),
        ),
    ]
