# Generated by Django 5.2.8 on 2025-11-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_car_car_class'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='passengertravel',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='passengertravel',
            name='status',
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='from_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='to_location',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('arrived', 'Arrived'), ('started', 'Started'), ('on_the_way', 'On The Way'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='created', max_length=10)),
                ('order_type', models.CharField(choices=[('travel', 'Travel'), ('delivery', 'Delivery')], default='travel', max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
