# Generated by Django 5.2.9 on 2026-01-10 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_tariff_alter_cityprice_options_remove_cityprice_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Tarif', 'verbose_name_plural': 'Tariflar'},
        ),
        migrations.AlterField(
            model_name='route',
            name='from_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_city', to='bot_app.city', verbose_name='Boshlanish'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_city', to='bot_app.city', verbose_name='Tugash'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cityprice',
            constraint=models.UniqueConstraint(fields=('route', 'tariff'), name='unique_route_tariff'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('from_city', models.F('to_city')), _negated=True), name='check_from_to_not_equal', violation_error_message="Boshlanish va tugash shaharlari bir xil bo'lishi mumkin emas!"),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(condition=models.Q(('from_city__isnull', False), ('to_city__isnull', False)), fields=('from_city', 'to_city'), name='unique_from_to_cities', violation_error_message="Bu yo'nalish mavjud"),
        ),
    ]
