# Generated by Django 5.2.9 on 2026-01-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_passengertodriverreview_uniq_review_per_order_per_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerpost',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
