# Generated by Django 5.2.9 on 2026-01-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_alter_route_options_alter_tariff_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
