# Generated by Django 5.2.8 on 2025-11-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_remove_passengerpost_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerpost',
            name='from_location',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='passengerpost',
            name='to_location',
            field=models.CharField(default={}),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='from_location',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='to_location',
            field=models.CharField(default={}),
        ),
    ]
