# Generated by Django 5.2.9 on 2026-01-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_alter_passengerpost_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerreject',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
