# Generated by Django 5.2.8 on 2025-11-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_driver_alter_botclient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user',
            new_name='telegram_id',
        ),
    ]
