# Generated by Django 5.2.9 on 2026-01-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_cashback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerToDriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.TextField(default='')),
                ('rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.driver')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.passenger')),
            ],
            options={
                'verbose_name': "Buyurtmaga yo'lovchi izohi",
                'verbose_name_plural': "Buyurtmaga yo'lovchi izohlari",
            },
        ),
    ]
