# Generated by Django 5.2.9 on 2026-01-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_alter_passengerreject_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengertodriverreview',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
