# Generated by Django 5.2.8 on 2025-11-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_alter_passengerpost_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerpost',
            name='to_location',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='to_location',
            field=models.JSONField(default=dict),
        ),
    ]
