# Generated by Django 5.2.8 on 2025-11-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_alter_car_driver_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='translate',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
