# Generated by Django 5.2.9 on 2026-01-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_passengertodriverreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengertodriverreview',
            name='rate',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=5),
        ),
    ]
