# Generated by Django 5.2.9 on 2026-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_passengertodriverreview_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengertodriverreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
