# Generated by Django 5.2.8 on 2025-11-30 17:16

import bot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_alter_passengerpost_to_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerpost',
            name='from_location',
            field=models.JSONField(default=bot_app.models.Location),
        ),
        migrations.AlterField(
            model_name='passengerpost',
            name='to_location',
            field=models.JSONField(default=bot_app.models.Location),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='from_location',
            field=models.JSONField(default=bot_app.models.Location),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='to_location',
            field=models.JSONField(default=bot_app.models.Location),
        ),
    ]
