# Generated by Django 5.2.9 on 2026-01-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_alter_passengertodriverreview_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengertodriverreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.order'),
        ),
    ]
