# Generated by Django 5.2.9 on 2026-01-22 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_alter_passengertodriverreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='amount',
            field=models.IntegerField(default=150000, verbose_name="Haydovchi mablag'i"),
        ),
        migrations.AlterField(
            model_name='driver',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.route', verbose_name="Yo'nalishi"),
        ),
    ]
