# Generated by Django 5.2.9 on 2026-01-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_alter_driver_amount_alter_driver_route_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='last_online_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Online bo'lgan vaqt"),
        ),
    ]
