# Generated by Django 5.2.9 on 2026-01-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_passengertodriverreview_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback', models.FloatField(default=0.001, verbose_name='Safar uchun keshbek')),
            ],
            options={
                'verbose_name': 'SOZLAMA',
                'verbose_name_plural': 'SOZLAMALAR',
            },
        ),
    ]
