# Generated by Django 5.2.9 on 2026-01-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_categories_driver_last_online_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
