# Generated by Django 5.2.8 on 2025-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_alter_passengerpost_from_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('total_rides', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField(default=5)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.RemoveField(
            model_name='botclient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='botclient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='botclient',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='botclient',
            name='total_rides',
        ),
    ]
