# Generated by Django 5.2.9 on 2026-01-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_adminsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsettings',
            old_name='cashback',
            new_name='order_cashback',
        ),
    ]
