# Generated by Django 5.2.9 on 2026-01-26 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='last_online_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Online bo'lgan vaqt"),
            preserve_default=False,
        ),
    ]
