# Generated by Django 5.2.9 on 2026-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_rename_cashback_adminsettings_order_cashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='order_cashback',
            field=models.FloatField(default=0.001, verbose_name='Safar uchun keshbek %'),
        ),
    ]
