# Generated by Django 5.2.9 on 2026-01-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_alter_adminsettings_order_cashback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSettings',
        ),
    ]
