# Generated by Django 5.2.9 on 2026-01-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_alter_driver_last_online_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='last_online_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Online bo'lgan vaqt"),
        ),
    ]
