# Generated by Django 5.2.8 on 2025-11-30 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_alter_passenger_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_rides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='amount',
            field=models.IntegerField(default=150000),
        ),
    ]
