# Generated by Django 5.2.8 on 2025-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0013_driver_full_name_driver_phone_driver_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botclient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bot foydalanuvchisi', 'verbose_name_plural': 'Bot foydalanuvchilari'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shahar', 'verbose_name_plural': 'Shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at'], 'verbose_name': 'Haydovchi', 'verbose_name_plural': 'Haydovchilar'},
        ),
        migrations.AlterModelOptions(
            name='drivertransaction',
            options={'ordering': ['-created_at'], 'verbose_name': "Haydovchi pul o'tkazmasi", 'verbose_name_plural': "Haydovchi pul o'tkazmalari"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['-rating'], 'verbose_name': "Yo'lovchi", 'verbose_name_plural': "Yo'lovchilar"},
        ),
        migrations.AlterModelOptions(
            name='passengerpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pochta', 'verbose_name_plural': 'Pochtalar'},
        ),
        migrations.AlterModelOptions(
            name='passengertravel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sayohat', 'verbose_name_plural': 'Sayohatlar'},
        ),
        migrations.AddField(
            model_name='passengertravel',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('arrived', 'Arrived'), ('started', 'Started'), ('ended', 'Ended'), ('rejected', 'Rejected')], default='created', max_length=10),
        ),
    ]
