# Generated by Django 5.2.9 on 2026-01-17 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0013_delete_adminsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cashback', models.FloatField(default=0.001, verbose_name='Safar uchun keshbek %')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_settings', to='bot_app.route')),
            ],
            options={
                'verbose_name': 'SOZLAMA',
                'verbose_name_plural': 'SOZLAMALAR',
            },
        ),
    ]
