# Generated by Django 5.2.9 on 2026-01-26 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0013_alter_driver_last_online_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='last_online_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Online bo'lgan vaqt"),
        ),
    ]
