# Generated by Django 5.2.9 on 2025-12-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_alter_botclient_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='economy', max_length=200),
        ),
        migrations.AlterField(
            model_name='passengertravel',
            name='travel_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='standard', max_length=200),
        ),
    ]
