# Generated by Django 5.2.9 on 2026-01-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_adminsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminSettings',
            new_name='RouteCashback',
        ),
        migrations.AlterModelOptions(
            name='routecashback',
            options={'verbose_name': "Yo'nalish keshbeki", 'verbose_name_plural': "Yo'nalish keshbeklari"},
        ),
    ]
