# Generated by Django 5.2.9 on 2025-12-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0015_driver_profile_image_alter_car_car_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='DriverGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('telegram_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_app.driver')),
            ],
        ),
    ]
