# Generated by Django 5.2.9 on 2026-01-17 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0015_rename_adminsettings_routecashback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerpost',
            old_name='price',
            new_name='cashback',
        ),
        migrations.RenameField(
            model_name='passengertravel',
            old_name='price',
            new_name='cashback',
        ),
        migrations.RemoveField(
            model_name='passengerpost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='passengertravel',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='passengertravel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='passengerpost',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.route'),
        ),
        migrations.AddField(
            model_name='passengerpost',
            name='tariff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.tariff'),
        ),
        migrations.AddField(
            model_name='passengertravel',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.route'),
        ),
        migrations.AddField(
            model_name='passengertravel',
            name='tariff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.tariff'),
        ),
    ]
