# Generated by Django 5.2.9 on 2025-12-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0016_remove_driver_profile_image_drivergallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers_from', related_query_name='driver_from', to='bot_app.city'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers_to', related_query_name='driver_to', to='bot_app.city'),
        ),
        migrations.CreateModel(
            name='CityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comfort', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.city')),
            ],
            options={
                'verbose_name': 'Shahar narxlari',
                'verbose_name_plural': 'Shahar narxlari',
            },
        ),
    ]
