# Generated by Django 5.2.9 on 2026-01-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0016_rename_price_passengerpost_cashback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengertravel',
            name='travel_class',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.tariff'),
        ),
    ]
