# Generated by Django 5.2.9 on 2025-12-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0017_alter_driver_from_location_alter_driver_to_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='from_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_from', related_query_name='driver_from', to='bot_app.city'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='to_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_to', related_query_name='driver_to', to='bot_app.city'),
        ),
    ]
