# Generated by Django 5.2.9 on 2026-01-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0017_remove_passengertravel_travel_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerpost',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='passengerpost',
            old_name='tariff_id',
            new_name='tariff',
        ),
        migrations.RenameField(
            model_name='passengertravel',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='passengertravel',
            old_name='tariff_id',
            new_name='tariff',
        ),
    ]
