# Generated by Django 5.2.9 on 2026-01-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0018_rename_route_id_passengerpost_route_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerpost',
            old_name='commit',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='passengertodriverreview',
            old_name='commit',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='passengertravel',
            old_name='commit',
            new_name='comment',
        ),
    ]
