# Generated by Django 5.2.9 on 2026-01-17 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0019_rename_commit_passengerpost_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.tariff'),
        ),
        migrations.AddField(
            model_name='driver',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.route'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('comfort', 'Comfort')], max_length=200),
        ),
    ]
