# Generated by Django 5.2.9 on 2026-01-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0020_car_tariff_driver_route_id_alter_car_car_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='standard', max_length=200),
        ),
    ]
