# Generated by Django 5.2.9 on 2026-01-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0022_alter_car_car_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerpost',
            name='travel_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='economy', max_length=50),
        ),
        migrations.AddField(
            model_name='passengertravel',
            name='travel_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('comfort', 'Comfort')], default='economy', max_length=50),
        ),
    ]
